language: r
sudo: true
cache: packages

warnings_are_errors: false

r_packages:
  - Cairo
  - GGally
  - ggrepel
  - intergraph
  - magrittr
  - network
  - rmarkdown
  - survival

bioc_packages:
  - BiocInstaller
  - limma

r_github_packages:
  - cran/RUnit
  - ropengov/sorvi
  - microbiome/microbiome  
  - microbiome/HITChipDB
  - zdk123/SpiecEasi
  - briatte/ggnet
  - earlywarningtoolbox/earlywarnings-R/earlywarnings

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS="--no-manual"
     - R_CHECK_ARGS="--no-manual --as-cran"
     - secure: "g2A6DMbAb1ZsJZzACj4rtiIS7h0MD5AZU63GEIPX+Zm/owkkKvY0U7XW4+NbnvqzAoTVKjnhK4eRJ0UD+NPwn++uN4dSRkv+4ZmVdauz3VsSqKBcTSkvXDNt+0YMPwccdwSj9vt0k8Xc6ga0rsWvbtPLYZeLvPmKJxg8m0GxS04="     

before_install:
  - pip install --user codecov
  - chmod 755 ./.push_gh_pages.sh
  - sudo apt-get install -y tcl tk tk-dev

after_success:	
  - bash <(curl -s https://codecov.io/bash)
  - ./.push_gh_pages.sh

