language: r
sudo: required
cache: packages
warnings_are_errors: false
r_packages:
- ade4
- bayesm
- Cairo
- compositions
- diptest
- dplyr
- energy
- fastcluster
- FD
- GGally
- ggplot2
- ggrepel
- Hmisc
- intergraph
- knitcitations
- knitr
- lme4
- magrittr
- maptree
- MASS
- Matrix
- minet
- mixOmics
- moments
- network
- plyr
- qvalue
- reshape2
- rmarkdown
- robustbase
- rpart
- scales
- survival
- tensorA
- tgp
- tidyr
- vegan
- WGCNA
bioc_packages:
- BiocInstaller
- limma
- phyloseq
r_github_packages:
- slowkow/ggrepel
- cran/RUnit
- ropengov/sorvi
- microbiome/microbiome
- zdk123/SpiecEasi
- briatte/ggnet
- earlywarningtoolbox/earlywarnings-R/earlywarnings

env:
  global:
  - WARNINGS_ARE_ERRORS=1
  - r_build_args: "--no-build-vignettes --no-manual --no-resave-data"
  - r_check_args: "--no-build-vignettes --no-manual --as-cran"
  - GITHUB_REPO: microbiome/microbiome
  - secure: kivwIFvX65gp1xOYQyfdXwr4/FuUFfS27Aqug19K7euNbz8oEuwDiIId+VNBdiTJ+Wyn267gepf/Uc9cqyimvx4d+r2LMveNTBhAfN5cXt3gqEzqszZYwWlTbBojHsz03LMDgzNtEXto98KCB8zaghAP2Zdq42RBjuzGa28F650=
  - secure: kuJcKMx91ikYgbamYDep0b/44kXiHCJU5vn832tVWMm9VEYNqnOtfiWrJinFcwcTNsoVbQvH07xz1VobSFCsGn6bjxxAoM3WLe34+SWp8eWiZ8GQHU4tsVcxCJw+ZTzSS+cLs+JguQs+WCKU/0QOWRY77fUbBQg6v7B0z2Wy8N0=

before_install:
- pip install --user codecov
- chmod 755 ./.push_gh_pages.sh
- chmod 755 ./.deploy.sh
- sudo apt-get install -y tcl tk tk-dev

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash .push_gh_pages.sh
  #- bash .deploy.sh
