language: r
sudo: false
cache: packages

warnings_are_errors: false

before_install:
  - pip install --user codecov
  
r_packages:
  - Cairo

bioc_packages:
  - BiocInstaller
      
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS="--no-manual"
     - R_CHECK_ARGS="--no-manual --as-cran"

