xlanguage: r
sudo: true
cache: packages


warnings_are_errors: false

before_install:
  - chmod 755 ./.push_gh_pages.sh
  - sudo apt-get install -y tcl tk tk-dev

r_packages:
  - Cairo
  - GGally
  - ggrepel
  - intergraph
  - magrittr
  - network
  - rmarkdown
  - survival

bioc_packages:
  - BiocInstaller
  - limma

r_github_packages:
  - cran/RUnit
  - ropengov/sorvi
  - microbiome/microbiome  
  - microbiome/HITChipDB
  - zdk123/SpiecEasi
  - briatte/ggnet
  - earlywarningtoolbox/earlywarnings-R/earlywarnings
  
after_success:
  - ./.push_gh_pages.sh

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS="--no-manual"
     - R_CHECK_ARGS="--no-manual --as-cran"
     - secure: "RzcTXPJ0qxNYSd/38GAgknrmRRdRc+ISolJfnALXkwHm5tuMtpyDdUT6FH2oTLg9MUwAPvfDISqX6wAr/Jk9QN71xvU7QU8DQQbCBP40P5MYIZ8rfzSCCXNjX39egv3458YdvYjWSyHU5R31QZrKEqKKRFBGJzTiQDZT+PLACRg="
