language: r
install:
  - npm install
script:
  - make check
  - make generate
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
  # - bash deploy.sh
env:
  global:
    secure: dcX1sBTNtA9ON8nQylCJLtoF9HVx7rlh/arJdCrGl40XmqpuNRvDKQJWq2on09sIBLQupHu6XfQm55TmEiuY2zBybedOdcK13rLShMLEEatICAlnIhMtPM11vKhDAyiYi+iXfaIjYm2ApSiuPhsEjOAr1vmdnnPc1vFmrWH6AuE=
